name: Heroku Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      sh -c "curl --silent --show-error --fail ${{secrets.HEROKU_LINK}}" 
