name: Heroku Awake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
      
jobs:
    run:
        name: Ping
        runs-on: ubuntu-latest
        steps:
            - name: Ping
              run: |
                  sh -c "curl --silent ${{secrets.HEROKU_LINK}}" 
